name: Publish package to PyPI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+[a-c][0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+alpha[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+beta[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

permissions: {}

jobs:
  build_and_publish:
    runs-on: ubuntu-24.04
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          version: "0.11.26"
          enable-cache: false
          python-version: "3.12"
      - run: uv build --verbose
      - uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
